---
- name: Gather Installed Softwares from Windows Hosts
  hosts: windows
  gather_facts: no

  tasks:
    - name: Create the software file at the start of the play
      ansible.builtin.copy:
        content: ""
        dest: "/root/host-inventory-list/Windows_ServerApps.csv"
        force: yes
      delegate_to: localhost
      run_once: true

    - name: Create the windows server names file at the start of the play
      ansible.builtin.copy:
        content: ""
        dest: "/root/host-inventory-list/all_windows_server_names.txt"
        force: yes
      delegate_to: localhost
      run_once: true

    - name: Write aggregated Windows server names
      ansible.builtin.lineinfile:
        path: /root/host-inventory-list/all_windows_server_names.txt
        line: "{{ inventory_hostname }}"
        insertafter: EOF
      delegate_to: localhost

    - name: Get the installed Softwares
      ansible.windows.win_shell: |
        $hostname = $env:COMPUTERNAME

        $paths = @(
          "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*",
          "HKLM:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*"
        )

        foreach ($path in $paths) {
          Get-ItemProperty $path -ErrorAction SilentlyContinue |
          Where-Object { $_.DisplayName } |
          ForEach-Object {
            $NAME = ($_.DisplayName -replace ',', ' ')
            $VERSION = ($_.DisplayVersion -replace ',', ' ')
            $SUMMARY = ($_.Publisher -replace ',', ' ')
            $INSTALLTIME = ($_.InstallDate -replace ',', ' ')

            "$NAME,$VERSION,$SUMMARY,$INSTALLTIME,$hostname"
          }
        }
      register: installed_softwares
      changed_when: false

    - name: Append installed softwares to file in /root/host-inventory-list/
      ansible.builtin.blockinfile:
        path: /root/host-inventory-list/Windows_ServerApps.csv
        block: "{{ installed_softwares.stdout }}"
        marker: ""
        insertafter: EOF
      delegate_to: localhost